# See config.example.yml for documentation.
object: orig/GYQE01/sys/main.dol
hash: 8a7f951cd701a9db6ed13a0bd59456d7a44b6fbb
mw_comment_version: 8

symbols: config/GYQE01/symbols.txt
splits: config/GYQE01/splits.txt

modules:
- object: orig/GYQE01/files/game.rel
  hash: 24a9d049c5620aa1dbc76aad7d3ed89ac06e01ac
  symbols: config/GYQE01/game/symbols.txt
  splits: config/GYQE01/game/splits.txt

- object: orig/GYQE01/files/menus.rel
  hash: ae9bdc7539687948695e55e5287eab8d899ce46a
  symbols: config/GYQE01/menus/symbols.txt
  splits: config/GYQE01/menus/splits.txt

- object: orig/GYQE01/files/challenge.rel
  hash: 1078bab4fa28a1ca4df173267205559de3fc0cb8
  symbols: config/GYQE01/challenge/symbols.txt
  splits: config/GYQE01/challenge/splits.txt
